--view lay danh sách nhân viên
CREATE OR REPLACE VIEW ATBMHTTT_VIEW_NHANVIEN AS
SELECT MANV,TENNV,PHAI,NGAYSINH,DIACHI,SODT,VAITRO,MANQL,PHG
FROM ATBMHTTT_TABLE_NHANVIEN;
/

--view lay tat ca phong ban
CREATE OR REPLACE VIEW v_ShowAllPhongBan
AS
SELECT * FROM ATBMHTTT_TABLE_PHONGBAN;
/
--view lay ten va ma cua tat ca truong phong
CREATE OR REPLACE VIEW v_ShowAllTruongPhong
AS
SELECT MANV,TENNV FROM ATBMHTTT_TABLE_NHANVIEN WHERE VAITRO = 'TRƯỞNG PHÒNG';
/
 --view lấy tên và mã của tất cả  quản lý trực tiếp
CREATE OR REPLACE VIEW v_ShowAllQuanLyTrucTiep
AS
SELECT MANV,TENNV FROM ATBMHTTT_TABLE_NHANVIEN WHERE VAITRO = 'QUẢN LÝ TRỰC TIẾP';
/
--view lay tat ca de an
CREATE OR REPLACE VIEW v_ShowAllDeAn
AS
select * from ATBMHTTT_TABLE_DEAN ORDER BY MADA ASC;
/


--procedure
-- proc lay thong tin cua 1 nhan vien
CREATE OR REPLACE PROCEDURE sp_GetDetalEmployee(EMP OUT SYS_REFCURSOR,Ma NVARCHAR2)
AS

BEGIN
    
    IF Ma = sys_context('userenv','session_user') then
        OPEN EMP FOR
        SELECT nv.*,pb.TENPB FROM ATBMHTTT_TABLE_NHANVIEN nv,ATBMHTTT_TABLE_PHONGBAN pb WHERE nv.PHG =pb.MAPB and  MANV =Ma;  
    ELSE    
        OPEN EMP FOR
        SELECT nv.*,pb.TENPB FROM ATBMHTTT_VIEW_NHANVIEN nv,ATBMHTTT_TABLE_PHONGBAN pb WHERE nv.PHG =pb.MAPB and  MANV = Ma;

    END IF;
END;


-- proc cap nhat thong tin cua 1 phong
CREATE OR REPLACE PROCEDURE sp_UPDATEROOM(TP  NVARCHAR2,TrP  CHAR,MP  CHAR)
AS
BEGIN
    UPDATE ATBM_20H3T_22.ATBMHTTT_TABLE_PHONGBAN
    SET TRPHG=TrP,
        TENPB=TP
    WHERE MAPB=MP;
END;

-- proc thêm 1 phong ban
CREATE OR REPLACE PROCEDURE sp_INSERTROOM(TP  NVARCHAR2,TrP  CHAR,MP  CHAR)
AS
BEGIN
   INSERT INTO ATBMHTTT_TABLE_PHONGBAN(MAPB, TENPB, TRPHG) VALUES (MP, TP, TrP);
END;

--proc cập nhật 1 nhan vien
CREATE OR REPLACE PROCEDURE sp_UPDATEEMPLOYEE(ma  NVARCHAR2,ht  CHAR,p  CHAR,ns  CHAR,dc  CHAR,sdt  CHAR,vt  CHAR,ql  CHAR,ph  CHAR)
AS
BEGIN
    UPDATE ATBMHTTT_TABLE_NHANVIEN 
    SET TENNV =ht,PHAI =p,NGAYSINH = TO_DATE(ns,'DD-MM-YYYY'),DIACHI =dc,SODT =sdt,VAITRO =vt,MANQL =ql,PHG =ph
    WHERE MANV = ma;
END;

--proc thêm 1 nhân viên
CREATE OR REPLACE PROCEDURE sp_INSERTMPLOYEE(ma  NVARCHAR2,ht  CHAR,p  CHAR,ns  CHAR,dc  CHAR,sdt  CHAR,vt  CHAR,ql  CHAR,ph  CHAR)
AS
BEGIN
    INSERT INTO ATBMHTTT_TABLE_NHANVIEN(MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, LUONG, PHUCAP, VAITRO, MANQL, PHG)
VALUES(ma, ht, p, TO_DATE(ns,'DD-MM-YYYY'), dc, sdt, NULL, NULL, vt, ql,ph);
END;

--proc lấy chi tiết 1 phòng ban
CREATE OR REPLACE PROCEDURE sp_GetRoom(Room OUT SYS_REFCURSOR,Ma IN CHAR)
AS
BEGIN
    OPEN Room FOR
    SELECT * FROM ATBMHTTT_TABLE_PHONGBAN WHERE MAPB = Ma;
END;
/


--NHÂN SỰ------------------------------------------------------------------
CREATE ROLE ATBMHTTT_ROLE_NHANSU;
CREATE USER NV018 IDENTIFIED BY 1;
GRANT CREATE SESSION TO NV018;
GRANT ATBMHTTT_ROLE_NHANSU TO NV018;

--CẤP QUYỀN---------------------------------------------------------------------
grant select on ATBMHTTT_VIEW_NHANVIEN to ATBMHTTT_ROLE_NHANSU;
grant select on v_ShowAllPhongBan to ATBMHTTT_ROLE_NHANSU;
grant select on v_ShowAllDeAn to ATBMHTTT_ROLE_NHANSU;
grant select on v_ShowAllTruongPhong to ATBMHTTT_ROLE_NHANSU;
grant select on v_ShowAllQuanLyTrucTiep to ATBMHTTT_ROLE_NHANSU;
--grant quyen update tren bang
GRANT UPDATE (NGAYSINH,SODT,DIACHI) on ATBM_20H3T_22.ATBMHTTT_TABLE_NHANVIEN to ATBMHTTT_ROLE_NHANSU;
--grant quyen execute procedure
GRANT EXECUTE ON ATBM_20H3T_22.proc_GetInforEmployee TO ATBMHTTT_ROLE_NHANSU;
GRANT EXECUTE ON ATBM_20H3T_22.sp_UPDATEROOM TO ATBMHTTT_ROLE_NHANSU;
GRANT EXECUTE ON ATBM_20H3T_22.sp_INSERTROOM TO ATBMHTTT_ROLE_NHANSU;
GRANT EXECUTE ON ATBM_20H3T_22.sp_UPDATEEMPLOYEE TO ATBMHTTT_ROLE_NHANSU;
GRANT EXECUTE ON ATBM_20H3T_22.sp_INSERTMPLOYEE TO ATBMHTTT_ROLE_NHANSU;
GRANT EXECUTE ON ATBM_20H3T_22.sp_GetRoom TO ATBMHTTT_ROLE_NHANSU;