--GIÁM ĐỐC----------------------------------------------------------------------
CREATE ROLE ATBMHTTT_ROLE_GIAMDOC;
CREATE USER NV023 IDENTIFIED BY 1234;
GRANT CREATE SESSION TO NV023;
GRANT ATBMHTTT_ROLE_GIAMDOC TO NV023;
--cẤP QUYỀN---------------------------------------------------------------------
GRANT SELECT ON v_ShowAllEmployee TO ATBMHTTT_ROLE_GIAMDOC;
GRANT EXECUTE ON sp_Get1Employee TO ATBMHTTT_ROLE_GIAMDOC;
GRANT EXECUTE ON sp_GetRoom TO ATBMHTTT_ROLE_GIAMDOC;
GRANT EXECUTE ON sp_GetRoomByName TO ATBMHTTT_ROLE_GIAMDOC;
GRANT EXECUTE ON sp_GetDeAn TO ATBMHTTT_ROLE_GIAMDOC;
GRANT SELECT ON v_ShowAllDeAn TO ATBMHTTT_ROLE_GIAMDOC;
GRANT SELECT ON v_ShowAllPhanCong TO ATBMHTTT_ROLE_GIAMDOC;
GRANT SELECT ON v_ShowAllPhongBan TO ATBMHTTT_ROLE_GIAMDOC;

--TRƯỞNG ĐỀ ÁN------------------------------------------------------------------
CREATE USER NV028 IDENTIFIED BY 1234;
GRANT CREATE SESSION TO NV028;
--CẤP QUYỀN---------------------------------------------------------------------
GRANT ATBMHTTT_ROLE_TRUONGDEAN TO NV028;
GRANT EXECUTE ON sp_GetDeAn TO ATBMHTTT_ROLE_TRUONGDEAN;
GRANT EXECUTE ON sp_DELETEDEAN TO ATBMHTTT_ROLE_TRUONGDEAN;
GRANT SELECT ON v_ShowAllDeAn TO ATBMHTTT_ROLE_TRUONGDEAN;
GRANT EXECUTE ON sp_ADDDEAN TO ATBMHTTT_ROLE_TRUONGDEAN;
GRANT SELECT ON v_ShowAllPhanCong TO ATBMHTTT_ROLE_TRUONGDEAN;
GRANT SELECT ON v_ShowAllPhongBan TO ATBMHTTT_ROLE_TRUONGDEAN;
GRANT EXECUTE ON sp_UPDATEDEAN TO ATBMHTTT_ROLE_TRUONGDEAN;
GRANT SELECT ON v_ShowAllPhongBan TO ATBMHTTT_ROLE_TRUONGDEAN;
GRANT SELECT ON v_ShowAllDeAn TO ATBMHTTT_ROLE_TRUONGDEAN;
GRANT EXECUTE ON sp_GetRoom TO ATBMHTTT_ROLE_TRUONGDEAN;
GRANT EXECUTE ON sp_Get1Employee TO ATBMHTTT_ROLE_TRUONGDEAN;
GRANT EXECUTE ON sp_GetRoomByName TO ATBMHTTT_ROLE_TRUONGDEAN;