BEGIN
    DBMS_FGA.ADD_POLICY(
        object_schema   => 'ATBM_20H3T_22',
        object_name     => 'ATBMHTTT_TABLE_PHANCONG',
        policy_name     => 'AUDITING_PHANCONG_THOIGIAN',
        audit_column    => 'THOIGIAN',
        statement_types => 'UPDATE'
    );
END;
/

SELECT * FROM ATBMHTTT_TABLE_PHANCONG;

UPDATE ATBMHTTT_TABLE_PHANCONG
SET THOIGIAN = SYSDATE
WHERE MANV = 'NV001';

INSERT INTO ATBMHTTT_TABLE_PHANCONG VALUES ('NV001', 'DA004', SYSDATE);

SELECT *
FROM DBA_FGA_AUDIT_TRAIL
WHERE POLICY_NAME = 'AUDITING_PHANCONG_THOIGIAN';

-- AUDITING 2

BEGIN
    DBMS_FGA.ADD_POLICY(
        object_schema   => 'ATBM_20H3T_22',
        object_name     => 'ATBMHTTT_TABLE_NHANVIEN',
        policy_name     => 'AUDITING_NHANVIEN_LUONG_PHUCAP_NGUOIKHAC',
        audit_column    => 'LUONG, PHUCAP',
        statement_types => 'SELECT',
        audit_condition => 'MANV != SYS_CONTEXT(''USERENV'', ''SESSION_USER'')'
    );
END;
/
BEGIN
    DBMS_FGA.DROP_POLICY(
        object_schema   => 'ATBM_20H3T_22',
        object_name     => 'ATBMHTTT_TABLE_NHANVIEN',
        policy_name     => 'AUDITING_NHANVIEN_LUONG_PHUCAP_NGUOIKHAC'
    );
END;
/
SELECT *
FROM DBA_FGA_AUDIT_TRAIL
WHERE POLICY_NAME = 'AUDITING_NHANVIEN_LUONG_PHUCAP_NGUOIKHAC';

SELECT * FROM ATBM_20H3T_22.ATBMHTTT_TABLE_NHANVIEN WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');

-- AUDITING 3
BEGIN
    DBMS_FGA.ADD_POLICY(
        object_schema   => 'ATBM_20H3T_22',
        object_name     => 'ATBMHTTT_TABLE_NHANVIEN',
        policy_name     => 'AUDITING_NHANVIEN_CAPNHAT_LUONG_PHUCAP_NOT_TAICHINH',
        audit_column    => 'LUONG, PHUCAP',
        statement_types => 'UPDATE',
        audit_condition => 'VAITRO != ''TÀI CHÍNH'''
    );
END;
/
BEGIN
    DBMS_FGA.DROP_POLICY(
        object_schema   => 'ATBM_20H3T_22',
        object_name     => 'ATBMHTTT_TABLE_NHANVIEN',
        policy_name     => 'AUDITING_NHANVIEN_CAPNHAT_LUONG_PHUCAP_NOT_TAICHINH'
    );
END;
/
GRANT SELECT ON ATBMHTTT_TABLE_NHANVIEN TO NV013;

UPDATE ATBM_20H3T_22.ATBMHTTT_TABLE_NHANVIEN
SET LUONG = 1500
WHERE MANV = 'NV013';

SELECT *
FROM DBA_FGA_AUDIT_TRAIL
WHERE POLICY_NAME = 'AUDITING_NHANVIEN_CAPNHAT_LUONG_PHUCAP_NOT_TAICHINH';

SELECT * FROM atbmhttt_table_nhanvien WHERE VAITRO != 'TÀI CHÍNH';

CREATE USER NV013 IDENTIFIED BY NV013;
GRANT CREATE SESSION TO NV013;
GRANT UPDATE ON ATBMHTTT_TABLE_NHANVIEN TO NV013;

--AUDITING 4
SELECT * FROM SYS.AUD$;
--ĐĂNG NHẬP VỚI QUYỀN SYS MỚI LÀM DC
AUDIT SELECT ON SYS.AUD$ BY ACCESS;
ALTER SYSTEM SET AUDIT_TRAIL='DB' SCOPE=SPFILE;

SELECT * FROM SYS.AUD$ WHERE OBJ$NAME = 'AUD$';